flutter-form-builder-ecosystem/form_builder_validators

example/lib/home_page.dart
- Test pull request template
- Fix lints
=> style: Fix lint info

CHANGELOG.md, example/pubspec.lock, example/pubspec.yaml, pubspec.yaml
=> chore(release): 8.2.0

.github/workflows/base.yaml, README.md
- Refactor readme
- Add github generator release
=> Improve docs

CHANGELOG.md, example/pubspec.lock, pubspec.yaml
=> chore(release): 8.3.0

lib/l10n/intl_zh_Hant.arb, lib/localization/intl/messages_zh_Hant.dart
=> fix: intl zh-hant

README.md, example/pubspec.lock, lib/l10n/intl_ms.arb, lib/localization/intl/messages_all.dart, lib/localization/intl/messages_ms.dart, lib/localization/l10n.dart, pubspec.lock
Added support for Malay (ms) localization.
- Added intl_ms.arb file and run generate command. 
- Updated readme to add supported language.
=> added support for Malay (ms) localization

lib/src/form_builder_validators.dart
Added support for allowing empty in equalLength. Min length has already added allowEmpty but not in equalLength .
=> Add allow empty in equalLength

lib/src/form_builder_validators.dart
Close #10 
Document url validator
=> Improve url validator documentation

README.md, lib/l10n/intl_ta.arb, lib/localization/intl/messages.dart, lib/localization/intl/messages_ta.dart
Support for Tamil(ta) language.
=> Support for Tamil(ta) language

README.md, lib/l10n/intl_mn.arb, lib/localization/intl/messages.dart, lib/localization/intl/messages_mn.dart
=> Mongolian language support

lib/localization/intl/messages.dart, lib/localization/intl/messages_my.dart, lib/localization/intl/messages_ne.dart
Currently, the package doesn't support Nepali(ne) and Burmese(my) languages which was causing build errors(Language ne/my is not supported by FormBuilderLocalizations )while I was running my app. So, I have added support for both of the above-mentioned languages. Hope it will help the project achieve higher versatility with a wide range of supported languages.
=> Add nepali and burmese language support

README.md, lib/l10n/intl_al.arb, lib/localization/intl/messages.dart, lib/localization/intl/messages_al.dart
I saw Albanian was missing so I felt obliged to add it. Thanks for the great work guys!
Best regards,
Armando
=> added localisation for Albanian (al)

README.md, lib/l10n/intl_vi.arb, lib/localization/intl/messages.dart, lib/localization/intl/messages_vi.dart
Hi, 
I added translation for Vietnamese
=> support Vietnamese

.github/workflows/base.yaml, CHANGELOG.md, example/pubspec.lock, pubspec.lock, pubspec.yaml
Close #???
Connected to #???
Bumps version of intl to 0.18.0 to support Flutter 3.10.0
=> Bump intl to 0.18.0

lib/l10n/intl_mn.arb, lib/localization/intl/messages_mn.dart
Close #???
Connected to #???
Mongolian translation. Fixed typo
=> fixed mn translation typo

lib/l10n/intl_en.arb
=> fix: remove full stop at end of error message for max validation

.github/workflows/base.yaml, README.md, example/pubspec.lock, example/pubspec.yaml, pubspec.lock, pubspec.yaml
=> Docs improvements

README.md, lib/l10n/intl_fi.arb, lib/localization/intl/messages.dart, lib/localization/intl/messages_fi.dart
New language Finnish 
Added intl_fi.arb, executed flutter gen-l10n and created messages_fi.dart and created new messages.dart. Also updated README.md and added language code.
=> Feat: Added Finnish language

lib/l10n/intl_sv.arb
Close https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1378
Connected to #???
=> Change language code for Swedish

lib/l10n/intl_ku.arb
=> Add missing kurdish translations

CHANGELOG.md, README.md
Close #???
Connected to #???
@deandreamatias let me know if anything else is missing.
=> Add changelog and changes in readme

example/android/.gitignore, example/android/app/build.gradle, example/android/gradle.properties, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle, example/pubspec.yaml, pubspec.yaml
=> build: update minimal flutter version

lib/src/identity/password_validator.dart
Fix issue when password default error message isn't shown
=> Fix password validator
